Init
distributed-technologies/application-kafka-scada-event-source pull request #1
Opened 2021-05-25 14:40 UTC by jacobcrawford

Made the scada parquet to json event source application.

2021-05-25 17:43 UTC, skovbakke requested changes
It looks good, and I have only a few minor comments.

2021-05-25 17:43 UTC, skovbakke commented on scripts/scada_parquet_transformer.py
> +    df = table.to_pandas()
```suggestion
    df = pq.read_table(pa.BufferReader(message.value)).to_pandas()
```
By one-lineing this assignment we will get a smaller memory usage. Since the messages coming in are entire tables, it does not make sense to keep it in memmory both as a `table` and `df`.

2021-05-25 17:43 UTC, skovbakke commented on chart/templates/kafka-scada-json-deployment.yaml
> +        - "app/scada_parquet_transformer.py"
would it make more sense to have `ENTRYPOINT ['python', '/app/scada_parquet_transformer.py']` in the docker file. And not here? I do not see a situation where the image will be used with another entrypoint.

2021-05-25 17:43 UTC, skovbakke commented on chart/templates/kafka-scada-json-deployment.yaml
> +        - {{ .Values.topics.producer.name }}
These are arguments and I think it would be better to place them as such 
```suggestion
        args:
        - "{{ .Values.clusterName }}-kafka-bootstrap:9093"
        - {{ .Values.topics.consumer.name }}
        - {{ .Values.topics.producer.name }}
```

2021-05-25 17:43 UTC, skovbakke commented on Dockerfile
> +ENTRYPOINT ["sh"]
As mentioned in another comment, I think the entry point could be improved.

2021-05-26 11:21 UTC, jacobcrawford commented on scripts/scada_parquet_transformer.py
> +    df = table.to_pandas()
I always prefer readability over memory usage in applications where memory is not a critical factor.

2021-05-26 14:21 UTC, merged